### PR TITLE
Enable support for BEM.

### PR DESCRIPTION
**Pull request by timrombergjakobsson**

### CODE REVIEW

**Comment by timrombergjakobsson** [comment]
Hm verkar inte finnas config för detta projekt på ```circleci```

**Comment by timrombergjakobsson** [comment]
Vi behöver först definiera vilken stil av BEM som vi kör https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

```strict_BEM``` [link](https://en.bem.info/methodology/key-concepts/) el ```hyphenated_BEM```[link](https://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/).

**Comment by mmzoo** [comment]
I vote for http://getbem.com/naming that's called "hyphenated" I assume.

**Comment by mmzoo** [comment]
Please let's get rid of this rule, too https://github.com/bukowskis/style-guide/blob/73d8ca9b9ff2afaf5099cc417924085ed9110ea1/scss-lint.yml#L17 it was introduced due to a misunderstanding 

See http://getbem.com/faq/#css-nested-elements

**Comment by mmzoo** [comment]
Like so? https://github.com/bukowskis/style-guide/pull/27

**Comment by mmzoo** [comment]
Solved via https://github.com/bukowskis/style-guide/commit/67c351dfe0c8cb2a709408c7e912b7855d779b50

**Pull request closed without merging**
