### PR TITLE
Able to use Ruby 2.3 without everything exploding

### PR DESCRIPTION
**Pull request by mmzoo**

### CODE REVIEW

**Comment by yboulkaid** [comment]
:+1:

**Comment by bjornblomqvist** [comment]
Vad är meningen med den här regeln?

**Comment by mmzoo** [comment]
In Ruby 3 all Strings are going to be immutable. So you cannot do something like

``` ruby
# This will raise an exception in Ruby 3
"hello".gsub! 'o', 'a'
```

To be able to already work towards this goal, you can already activate this behavior in Ruby `2.3` by adding a comment at the top of your file. Rubocop complains if that comment is missing.

Now that we talked about it, maybe it's a good thing after all?

**Comment by bjornblomqvist** [comment]
Aha... Not something we have to worry about now. By the way, why do we use english when discussing this?

**Comment by mmzoo** [comment]
> Not something we have to worry about now

We have one repository that uses Ruby 2.3 so I get a lot of rubocop errors.

> By the way, why do we use english when discussing this?

This is a public repository. So I cannot tell you which repository it is that uses Ruby 2.3 ;)

**Comment by bjornblomqvist** [comment]
> We have one repository that uses Ruby 2.3 so I get a lot of rubocop errors.

No, i mean we don't have to worry about ruby 3 right now. So turn it off.

**Comment by timrombergjakobsson** [comment]
🚢

**Pull request merged**
