### PR TITLE
Deleted doubly-defined defaults

### PR DESCRIPTION
**Pull request by mmzoo**
This should be virtually equal to what we had before, but just defining where we differ from the standard is easier to maintain.

### CODE REVIEW

**Comment by mmzoo** [comment]
@timrombergjakobsson @yboulkaid Roughly like this.

**Comment by yboulkaid** [comment]
:+1:

**Comment by timrombergjakobsson** [comment]
Go for it!

**Comment by mmzoo** [comment]
Thanks!

**Pull request merged**
