### PR TITLE
Cop updates

### PR DESCRIPTION
**Pull request by kitofr**
Updated to use new cops etc.
Hopefully hound agrees.

### CODE REVIEW

**Comment by kitofr** [comment]
Can @yboulkaid verify that this works somehow?

**Comment by yboulkaid** [comment]
Wow, I somehow didn't see this.
Hound is also on the latest version of rubocop (0.37.2 https://github.com/houndci/hound/commit/efacf3957afd339f5ad2b8a191f0908a5511c0e4 ) so this should work. Let's see

**Comment by yboulkaid** [comment]
And it's working indeed. Closing

**Comment by kitofr** [comment]
:+1:

**Pull request merged**
