### PR TITLE
Less fuss about specs

### PR DESCRIPTION
**Pull request by pidu**
I hope we can agree that obsessing about Metrics/LineLength and
Metrics/BlockLength doesn't add alot of value when it comes to our
specs.

### CODE REVIEW

**Review by mmzoo — CHANGES_REQUESTED** [review]
Rubocop itself has [these exceptions](https://github.com/bbatsov/rubocop/blob/0fb79a25d3ab20b823426223ca5c24640890d072/.rubocop.yml#L35-L39):

```
Lint/AmbiguousBlockAssociation
Metrics/BlockLength
Metrics/ModuleLength
```

So I'm fine with having those. 

But I do not agree with disabling `Metrics/LineLength` indiscriminately just for specs. Either we agree on a line length for all our ruby files or not. I would not include this in this PR but have that as a separate discussion.

**Comment by pidu** [comment]
Scenario: You have lots of legacy code to refactor. You need to touch the specs. You want to touch the specs as little as possible because you don't want to be changing code and specs at the same time (for obvious reasons). You're moving specs around because during refactoring you are extracting concerns from oversized classes and it makes sense to let the specs follow along.

**Comment by mmzoo** [comment]
So, in this particular scenario, it's not that line length is your problem, it's that you don't have the time to make large portions of legacy code to adhere to rubocop. That does not seem to justify a general disabling of a cop for everyone else in every spec file.

In this specific case I'd suggest a minimal PR that just does the moving around of stuff from file to file and simply ignore rubocop when merging that in. Either by ignoring it when they show up on github, or by adding `rubocop:disable` comments in the beginning of those spec files.

Either way, the block-length-ignore should be merged in the style guide. The line length can be a separate issue. Maybe even a group discussion.

**Comment by pidu** [comment]
Actually the problem was I want to change code without touching the specs more than necessary.

**Pull request merged**
